spring:
    application:
        name: FidsService
    datasource:
        url: jdbc:mysql://localhost:3306/test
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8084
