# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build and Deploy DCCT Service to Server

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12.0.2
      uses: actions/setup-java@v1
      with:
        java-version: 12.0.2
        java-package: jdk
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: SSH deploy to server
      uses: easingthemes/ssh-deploy@v2.1.4
      with: 
        SSH_PRIVATE_KEY: ${{ secrets.DCCT_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.DCCT_REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.DCCT_REMOTE_USER }}
        TARGET: ${{ secrets.DCCT_TARGET }}
    - name: Restart DCCT Service
      uses: garygrossgarten/github-action-ssh@v0.5.0
      with:
        host: ${{ secretes.DCCT_REMOTE_HOST }}
        username: ${{ secrets.DCCT_REMOTE_USER }}
        privateKey: ${{ secrets.DCCT_SSH_KEY }}
        command: sudo systemctl restart dcct.service
